#!/usr/bin/python

"""
    Configuration file storing the dictionary ast_units_dico.
        Key: Esprima simplified syntactic unit;
        Value: Unique integer.
"""


ast_units_dico = {
    'ArrayExpression': 0,
    'ArrayPattern': 5,
    'ArrowFunctionExpression': 0,
    'AssignmentExpression': 0,
    'AssignmentPattern': 5,
    'AwaitExpression': 0,
    'BinaryExpression': 0,
    'BlockComment': 7,
    'BlockStatement': 2,
    'BreakStatement': 2,
    'CallExpression': 0,
    'CatchClause': 13,
    'ClassBody': 14,
    'ClassDeclaration': 4,
    'ClassExpression': 0,
    'ConditionalExpression': 0,
    'ContinueStatement': 2,
    'DebuggerStatement': 2,
    'DoWhileStatement': 2,
    'EmptyStatement': 2,
    'ExportAllDeclaration': 4,
    'ExportDefaultDeclaration': 4,
    'ExportNamedDeclaration': 4,
    'ExportSpecifier': 6,
    'ExpressionStatement': 2,
    'ForInStatement': 2,
    'ForOfStatement': 2,
    'ForStatement': 2,
    'FunctionDeclaration': 4,
    'FunctionExpression': 0,
    'Identifier': 15,
    'IfStatement': 2,
    'Import': 16,
    'ImportDeclaration': 4,
    'ImportDefaultSpecifier': 6,
    'ImportNamespaceSpecifier': 6,
    'ImportSpecifier': 6,
    'LabeledStatement': 2,
    'LineComment': 7,
    'Literal': 3,
    'LogicalExpression': 0,
    'MemberExpression': 0,
    'MetaProperty': 17,
    'MethodDefinition': 18,
    'NewExpression': 0,
    'ObjectExpression': 0,
    'ObjectPattern': 5,
    'Program': 8,
    'Property': 9,
    'RestElement': 1,
    'ReturnStatement': 2,
    'SequenceExpression': 0,
    'SpreadElement': 1,
    'Super': 10,
    'SwitchCase': 11,
    'SwitchStatement': 2,
    'TaggedTemplateExpression': 0,
    'TemplateElement': 1,
    'TemplateLiteral': 3,
    'ThisExpression': 0,
    'ThrowStatement': 2,
    'TryStatement': 2,
    'UnaryExpression': 0,
    'UpdateExpression': 0,
    'VariableDeclaration': 4,
    'VariableDeclarator': 12,
    'WhileStatement': 2,
    'WithStatement': 2,
    'YieldExpression': 0,
}
