#!/usr/bin/python
 
'''
	Configuration file storing the mapping between every Esprima syntax element and their corresponding integer.
'''


astDico = { 
	'ImportDefaultSpecifier' : 33, 
	'ArrayPattern' : 1, 
	'ImportSpecifier' : 35, 
	'BinaryExpression' : 6, 
	'ContinueStatement' : 15, 
	'AssignmentExpression' : 3, 
	'TaggedTemplateExpression' : 54, 
	'ForStatement' : 26, 
	'Identifier' : 29, 
	'UnaryExpression' : 60, 
	'MemberExpression' : 39, 
	'ExportNamedDeclaration' : 21, 
	'TemplateLiteral' : 56, 
	'SpreadElement' : 50, 
	'Super' : 51, 
	'ArrayExpression' : 0, 
	'ReturnStatement' : 48, 
	'AssignmentPattern' : 4, 
	'ForInStatement' : 24, 
	'ImportDeclaration' : 32, 
	'TryStatement' : 59, 
	'ExportDefaultDeclaration' : 20, 
	'AwaitExpression' : 5, 
	'SwitchStatement' : 53, 
	'VariableDeclarator' : 63, 
	'YieldExpression' : 66, 
	'Literal' : 37, 
	'Program' : 45, 
	'ThisExpression' : 57, 
	'Import' : 31, 
	'ExpressionStatement' : 23, 
	'WhileStatement' : 64, 
	'ExportAllDeclaration' : 19, 
	'BreakStatement' : 8, 
	'Property' : 46, 
	'FunctionExpression' : 28, 
	'LabeledStatement' : 36, 
	'NewExpression' : 42, 
	'CallExpression' : 9, 
	'ThrowStatement' : 58, 
	'UpdateExpression' : 61, 
	'EmptyStatement' : 18, 
	'ForOfStatement' : 25, 
	'ImportNamespaceSpecifier' : 34, 
	'FunctionDeclaration' : 27, 
	'ClassDeclaration' : 12, 
	'ObjectPattern' : 44, 
	'LogicalExpression' : 38, 
	'DebuggerStatement' : 16, 
	'VariableDeclaration' : 62, 
	'ConditionalExpression' : 14, 
	'WithStatement' : 65, 
	'SwitchCase' : 52, 
	'ObjectExpression' : 43, 
	'DoWhileStatement' : 17, 
	'MethodDefinition' : 41, 
	'IfStatement' : 30, 
	'ExportSpecifier' : 22, 
	'SequenceExpression' : 49, 
	'CatchClause' : 10, 
	'ArrowFunctionExpression' : 2, 
	'MetaProperty' : 40, 
	'TemplateElement' : 55, 
	'RestElement' : 47, 
	'ClassExpression' : 13, 
	'ClassBody' : 11, 
	'BlockStatement' : 7, 
}