#!/usr/bin/python
 
'''
	Configuration file storing the dictionary astDico.
		Key: Esprima syntactical token;
		Value: Unique integer.
'''


astDico = { 
	'ArrayExpression' : 0, 
	'ArrayPattern' : 49, 
	'ArrowFunctionExpression' : 1, 
	'AssignmentExpression' : 2, 
	'AssignmentPattern' : 50, 
	'AwaitExpression' : 3, 
	'BinaryExpression' : 4, 
	'BlockComment' : 56, 
	'BlockStatement' : 22, 
	'BreakStatement' : 23, 
	'CallExpression' : 5, 
	'CatchClause' : 63, 
	'ClassBody' : 64, 
	'ClassDeclaration' : 42, 
	'ClassExpression' : 6, 
	'ConditionalExpression' : 7, 
	'ContinueStatement' : 24, 
	'DebuggerStatement' : 25, 
	'DoWhileStatement' : 26, 
	'EmptyStatement' : 27, 
	'ExportAllDeclaration' : 43, 
	'ExportDefaultDeclaration' : 44, 
	'ExportNamedDeclaration' : 45, 
	'ExportSpecifier' : 52, 
	'ExpressionStatement' : 28, 
	'ForInStatement' : 29, 
	'ForOfStatement' : 30, 
	'ForStatement' : 31, 
	'FunctionDeclaration' : 46, 
	'FunctionExpression' : 8, 
	'Identifier' : 65, 
	'IfStatement' : 32, 
	'Import' : 66, 
	'ImportDeclaration' : 47, 
	'ImportDefaultSpecifier' : 53, 
	'ImportNamespaceSpecifier' : 54, 
	'ImportSpecifier' : 55, 
	'LabeledStatement' : 33, 
	'LineComment' : 57, 
	'Literal' : 40, 
	'LogicalExpression' : 9, 
	'MemberExpression' : 10, 
	'MetaProperty' : 67, 
	'MethodDefinition' : 68, 
	'NewExpression' : 11, 
	'ObjectExpression' : 12, 
	'ObjectPattern' : 51, 
	'Program' : 58, 
	'Property' : 59, 
	'RestElement' : 19, 
	'ReturnStatement' : 34, 
	'SequenceExpression' : 13, 
	'SpreadElement' : 20, 
	'Super' : 60, 
	'SwitchCase' : 61, 
	'SwitchStatement' : 35, 
	'TaggedTemplateExpression' : 14, 
	'TemplateElement' : 21, 
	'TemplateLiteral' : 41, 
	'ThisExpression' : 15, 
	'ThrowStatement' : 36, 
	'TryStatement' : 37, 
	'UnaryExpression' : 16, 
	'UpdateExpression' : 17, 
	'VariableDeclaration' : 48, 
	'VariableDeclarator' : 62, 
	'WhileStatement' : 38, 
	'WithStatement' : 39, 
	'YieldExpression' : 18, 
}